apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoieGF2aWVyLmFuZ3VlcmEiLCJwYXNzd29yZCI6IkVRQlplMmpTMWFjRWNLU3I4UjFaIiwiZW1haWwiOiJjYXJvbGluYUBlbHNhbm93LmlvIiwiYXV0aCI6ImVHRjJhV1Z5TG1GdVozVmxjbUU2UlZGQ1dtVXlhbE14WVdORlkwdFRjamhTTVZvPSJ9fX0=
type: kubernetes.io/dockerconfigjson