secrets:
    G_CAPTCHA_KEY: ENC[AES256_GCM,data:O8DJ/mi9wDvawekDduxliLWxAQEeYFZ8s7Gn2XNw6TzdNQsLcodS9g==,iv:ihDwizTLIgN8F4EkDJvNFYKGHOUnnaSFLPuZIUQwU5Q=,tag:phOgTuZ4pDELG74w6+eQYA==,type:str]
    G_CAPTCHA_URL: ENC[AES256_GCM,data:HUFMNMQpWTCovgfyUhxEDVKFa2wKmannZ7B7Vkv4GYGr0it4Sdm0SLvmWZyMV+g=,iv:Qv8ETVH/MkSbwLVB26IjsacWPhAT3nb+KaVpeP9kYCM=,tag:hIeONkX7XaG3Z7hEyHAW9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-09-27T07:47:55Z'
    mac: ENC[AES256_GCM,data:hi1HvyYraxPfFb188uYNCWGf9WmSRjNB9d9GuIFXrZLRPkIx7dPRt7YA7DxQ+1MHwVsvaXFoYyTk9ILGQb6C2OpmOjGYXoiu6ISFX8G4Xenz29aIG3JMW+fq0sQMoKiHbs9jaQQKDh2O7yaeF1JayR7NCydS6zlqPkzTmqHr0fs=,iv:iynA7MJn8KkD4zNMTSTHVMwLGs5hLpPrf7GFzMDP5j4=,tag:oo2nKK9phPgn4zGaKgQPdg==,type:str]
    pgp:
    -   created_at: '2021-09-23T11:18:16Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hH4DTbnv4i6E7RESAgMEETVvrhbkZlt5bcX6hv5uCbu4q5Zd9BbiicXhlTx4Vfwt
            g0dqfqrAqbt6ChwcJmH3Rkyagp5zDBw60citPFv1aTCZHVPEJM5sqaag6Sh8wMPs
            u9jtd6fXAEiPBzkvYRalwHRaZrtWgKL61RkHV8gkQnHSXAE4OVBT7UafBOTeClU1
            KVuLuB37nRWvU3D8u3yFu+KQDdkOWfHugRCFdxKulCsw/1DnnNw8E3sMJNO57O13
            P5Zh/3NPGkycqyQvFVxjuY2Owgq2ceRjSchchkvl
            =Qz8v
            -----END PGP MESSAGE-----
        fp: 3CAFE454CD9F1977A155A2E715A79E9BF178C897
    unencrypted_suffix: _unencrypted
    version: '1.18'
