ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
  - host: vn-stag.elsaspeak.com
    paths:
    - /api

variables:
  ENVIRONMENT: development